version: '3'

services:

  apex:
    build:
      context: .
      dockerfile: ./bootstrap/docker/Dockerfile
    image: apex-1.6
    container_name: apex
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: apex
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./bootstrap/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - nginx
      - mysql
      - redis
    networks:
      - apex-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./bootstrap/docker/nginx:/etc/nginx/conf.d
      - ./bootstrap/docker/nginx:/var/log/nginx
    networks:
      - apex-network

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: apex
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: apex
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./bootstrap/docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - apex-network

  redis:
    image: redis:5.0
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - ./bootstrap/docker/redis/redis.conf:/etc/redis/redis.conf
    networks:
      - apex-network


#Docker Networks
networks:
  apex-network:
    driver: bridge


#Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local


