<?php
declare(strict_types = 1);

namespace apex\core\htmlfunc;

use apex\app;
use apex\emplate;


class password_meter 
{




/**
 * Process the HTML function. 
 *
 * Replaces the calling <a:function> tag with the contents generated by this 
 * HTML function. 
 *
 * @param string $html The contents of the TPL file, if exists, located at /views/htmlfunc/<package>/<alias>.tpl
 * @param array $data The attributes within the calling e:function> tag.
 *
 * @return string The resulting HTML code, which the <e:function> tag within the template is replaced with.
 */
public function process(string $html, array $data = array()):string
{ 

// Return
return $html;


    return $html;

}


}

